Support docker compose for local dev
the-blue-alliance/the-blue-alliance pull request #5173
Opened 2023-04-12 19:15 UTC by dracco1993

## Description
Add support for `docker-compose` to get local development environments running

## Motivation and Context
The current `vagrant` setup is inconsistent in working and can be confusing to debug if things go wrong.

## How Has This Been Tested?
It works for me locally.
Others should 100% try this locally as well, and let me know if there's issues.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

2023-04-12 19:17 UTC, dracco1993 commented on .gitattributes
> +*.sh text eol=lf
This is needed to make sure `sh` files have `LF` endings, since by default Windows tries to "be helpful" and convert them to `CRLF`.  🙄

2023-04-12 19:18 UTC, dracco1993 commented on docker-compose.yml
> +      dockerfile: ./ops/dev/docker/Dockerfile
Using this `image` is the end goal, but for now this forces the local image build, for development/testing of this actual PR.

2023-04-23 21:23 UTC, AGPapa submitted a review, later dismissed
This is great! I was not able to get vagrant up and running, but I have a local version of TBA now using this branch. Installing docker and running `docker-compose up` was all I needed to do.

+1 - I love it!

2023-04-23 21:35 UTC, dracco1993 commented
> This is great! I was not able to get vagrant up and running, but I have a local version of TBA now using this branch. Installing docker and running `docker-compose up` was all I needed to do.

That's awesome!  You don't know how happy it makes me to hear that!  lol

2023-04-23 22:03 UTC, phil-lopreiato commented
Very cool! This looks straightforward enough to me, but let me test this out locally before merging

2023-04-24 11:45 UTC, phil-lopreiato requested changes
Could you add a note in `doc/setup/Setup-Guide.md` about how to use this, with some example commands, and maybe note that it's still in beta?

2023-04-24 11:45 UTC, phil-lopreiato commented on docker-entry.sh
> +#! /bin/bash
move this into `/ops/dev/docker`

2023-05-10 00:19 UTC, dracco1993 commented on docker-entry.sh
> +#! /bin/bash
Moved in acf63bf

2023-05-10 02:32 UTC, phil-lopreiato approved these changes
:ship:

2023-05-10 02:32 UTC, merged