pwa thanks page
the-blue-alliance/the-blue-alliance pull request #6206
Opened 2024-08-10 07:53 UTC by shuklabhay

## Description
Created the react thanks page

## Motivation and Context
Eugene
[](https://github.com/the-blue-alliance/the-blue-alliance/issues/6168)

## How Has This Been Tested?
Local run

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would change API specifications or require data migrations)

2024-08-10 07:54 UTC, shuklabhay commented on pwa/app/routes/thanks.tsx
> +                  AndyMark
the only thing im unsure about is the list items dont have bullet points/indentation

2024-08-10 17:01 UTC, tervay requested changes
Appreciate the PR! Just a couple minor changes

2024-08-10 17:01 UTC, tervay commented on pwa/app/routes/thanks.tsx
> +                  React
More specifically using [Remix](https://remix.run/) now

2024-08-11 06:37 UTC, fangeugene commented on pwa/app/routes/thanks.tsx
> +            <a href="/https://github.com/the-blue-alliance/the-blue-alliance/graphs/contributors">
Leading slash breaks this link

2024-08-11 06:37 UTC, fangeugene requested changes
Minor fixes

2024-08-11 16:59 UTC, fangeugene approved these changes
ty!

2024-08-11 17:00 UTC, merged