[PWA] Add stats block to team pages
the-blue-alliance/the-blue-alliance pull request #6345
Opened 2024-08-21 22:04 UTC by tervay

2024-08-21 22:37 UTC, fangeugene commented on pwa/app/lib/matchUtils.ts
> +      m.actual_time !== null,
better to check that score is not `-1` to see if a match has been played. Not all matches have `actual_time` populated.

I'd create a helper called `hasBeenPlayed(match)` that checks if both red and blue scores are not `-1`.

2024-08-21 22:38 UTC, fangeugene commented on pwa/app/lib/utils.ts
> +  return record.ties > 0 ? `${wl}-${record.ties}` : wl;
I think keeping the 0 around is better for consistency.

2024-08-21 22:40 UTC, fangeugene requested changes
lg, couple nits

2024-08-21 23:48 UTC, tervay commented
Minor styling changes. felt like the `Event Results` text was obvious and unnecessary

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/d8a9a162-a77c-4a27-8104-63d41a932569)

![image](https://github.com/user-attachments/assets/45162e98-2bfe-4c0f-9872-ddbf3e454d9f)

![image](https://github.com/user-attachments/assets/9832340c-cb63-4a65-9c85-6d48b66595cf)

![image](https://github.com/user-attachments/assets/a24f330d-df73-4e22-8ba3-cee18aeadea6)
</details>

2024-08-21 23:55 UTC, tervay commented
Moved socials down to the bottom, right above the separator

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/9089e049-73b5-4a19-8461-caf561e3aa78)

![image](https://github.com/user-attachments/assets/0c4467b9-c0b8-402f-b43b-b4e2af8c4bff)

![image](https://github.com/user-attachments/assets/f1b41487-8271-4ae0-b12f-76f1845a6660)

![image](https://github.com/user-attachments/assets/d8845d58-a06c-41d4-b69b-75bad6eef799)

</details>

2024-08-22 00:03 UTC, fangeugene approved these changes

2024-08-22 00:08 UTC, merged