[WIP] Implement search on PWA
the-blue-alliance/the-blue-alliance pull request #6606
Opened 2024-10-22 01:49 UTC by tervay

2024-12-23 23:31 UTC, ofekashery commented on pwa/app/components/tba/searchbar.tsx
> +        inputRef.current?.focus();
It should be `focus` on open but `blur` on close.

2024-12-23 23:31 UTC, ofekashery commented on pwa/app/components/tba/searchbar.tsx
> +        inputRef.current?.focus();
Maybe consider use `<Popover />`, it'll handle you all the focus things like auto focus, blur, and focus trapping.

2024-12-23 23:35 UTC, ofekashery commented on pwa/app/components/tba/searchbar.tsx
> +      <CommandInput
I think it should be with `h-9`. This `h-11` height is really big.

2025-01-09 03:06 UTC, tervay commented on pwa/app/components/tba/searchbar.tsx
> +        inputRef.current?.focus();
It uses https://ui.shadcn.com/docs/components/command, tried with popover but it was kinda gross. This is also gross though. Open to refactoring it in the future.

2025-01-10 04:38 UTC, fangeugene requested changes

2025-01-10 04:38 UTC, fangeugene commented on pwa/app/components/tba/searchbar.tsx
> +  }, []);
Follow linter

2025-01-13 03:04 UTC, fangeugene approved these changes

2025-01-14 23:16 UTC, merged